version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
    command: yarn run dev

networks:
  default:
    external:
      name: bridge

















# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#       NODE_ENV: development
#       MONGODB_URI: mongodb://db:27017/mydatabase
#     command: yarn run dev
#     depends_on:
#       - db
#     networks:
#       - app-network

#   db:
#     image: mongo:4.4
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     networks:
#       - app-network

# volumes:
#   db-data:

# networks:
#   app-network:
#     driver: bridge
