name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env.production
        run: cp src/configs/.env.production.example src/configs/.env.production  # Ensure the .env file is copied to the correct location
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependancies
        run: yarn install
      - run: yarn build
      - run: yarn start
