name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          rm -f yarn.lock
          yarn install --no-lockfile

      - name: Generate TSOA routes and spec
        run: yarn tsoa:gen

      - name: Run tests
        run: yarn test
